import type { Metadata } from "next";
import { cn } from "@/lib/utils";

import "@/app/(main)/globals.css";
import { Toaster } from "sonner";
import {
  sirwan_bold,
  sirwan_light,
  sirwan_meduim,
  sirwan_reguler,
} from "../(main)/layout";

export const metadata: Metadata = {
  title: "Sign-in",
  description: "Generated by Avana Soft",
  manifest: "/manifest.json",
};

export default function AuthLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <div
      dir="rtl"
      className={cn(
        "min-h-screen bg-background  ",
        sirwan_reguler.variable,
        sirwan_meduim.variable,
        sirwan_bold.variable,
        sirwan_light.variable
      )}
    >
      {children}

      <Toaster dir="rtl" className="font-sirwan_reguler" />
    </div>
  );
}
